version: '3'

services:
  betternote-web:
    container_name: betternote-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    env_file:
      - .env
    stdin_open: true
    tty: true
